def dia = new Date().getDay()
def dias_letras =
   [1: "Lunes",
    2: "Martes",
    3: "Miercoles",
    4: "Jueves",
    5: "Viernes"]
pipeline {
    agent any
    stages {
	stage('Dias de la semana') {
            steps {
		    script {
			  def i = 1
			    while(i < 5) {
				  println dias_letras[i]
				   i = i + 1
			    }
		    }
            }
        }
        stage('Lunes') {
            steps {
		 echo ''
            }
        }
	stage('Martes') {
            steps {
              script {
                if (dias_letras[dia] == "Martes") 
                  println new Date()
              }
            }
        }
        stage('Miercoles') {
          steps {
		 echo ''
            }
        }
        stage('Jueves') {
          steps {
		 echo ''
            }
        }
        stage('Viernes') {
          steps {
		script {
			if (dias_letras[dia] == "Viernes") {
				def cause = currentBuild.rawBuild.getCause(Cause.UserIdCause)
				if (cause != null) {
    					def user = cause.userId ?: 'anonymous'
    					echo "started by ${user}"
				} else {
   					 echo "started some other way"
				}
			}
		  }
          }
        }
    }
}
