def dia = new Date().getDay()
def dias_letras =
   [1: "Lunes",
    2: "Martes",
    3: "Miercoles",
    4: "Jueves",
    5: "Viernes"]
pipeline {
    agent any
    stages {
	
        stage('Lunes') {
            steps {
		 script {
                	if (dias_letras[dia] == "Lunes") 
				echo ''
		 }
            }
        }
	stage('Martes') {
            steps {
              script {
                if (dias_letras[dia] == "Martes") 
                  println new Date()
              }
            }
        }
        stage('Miercoles') {
          steps {
		script {
                	if (dias_letras[dia] == "Miercoles") 
				echo ''
		 }
            }
        }
        stage('Jueves') {
          steps {
		 script {
                	if (dias_letras[dia] == "Jueves") 
				echo ''
		 }
            }
        }
        stage('Viernes') {
          steps {
		script {
			if (dias_letras[dia] == "Viernes") {
				def cause = currentBuild.rawBuild.getCause(Cause.UserIdCause)
				if (cause != null) {
    					def user = cause.userId ?: 'anonymous'
    					echo "started by ${user}"
				} else {
   					 echo "started some other way"
				}
			}
		  }
          }
        }
    }
}
